# Generated by Django 2.0.6 on 2018-07-03 01:14

import antigonovo.core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', antigonovo.core.managers.UserManager()),
            ],
        ),
    ]
