# Generated by Django 2.0.6 on 2018-07-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movel',
            name='foto',
            field=models.ImageField(max_length=200, null=True, upload_to='moveis/'),
        ),
    ]
