# Generated by Django 2.0.6 on 2018-07-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveis', '0002_movel_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movel',
            name='foto',
            field=models.ImageField(default='http://foo', max_length=200, upload_to='moveis/'),
        ),
    ]
