# Generated by Django 2.0.7 on 2018-07-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveis', '0003_auto_20180718_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movel',
            name='foto',
            field=models.ImageField(default='http://foo', upload_to='moveis/'),
        ),
    ]
